import { v as sleep } from "../../utils-BMRcljdi.js";
import { t as formatDocsLink } from "../../links-rWevNMpC.js";
import { a as hasConfiguredSecretInput, c as normalizeResolvedSecretInputString, l as normalizeSecretInputString } from "../../types.secrets-v6szeegc.js";
import { s as normalizeStringEntries } from "../../string-normalization-ColQTP6c.js";
import { r as buildChannelConfigSchema } from "../../config-schema-CNOE4EfY.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-DWChvwa8.js";
import { i as MSTeamsConfigSchema } from "../../zod-schema.providers-core-I4XTf8vQ.js";
import { a as withFileLock } from "../../file-lock-OriHUjLv.js";
import { a as resolveChannelEntryMatchWithFallback, n as buildChannelKeyCandidates, r as normalizeChannelSlug, s as resolveNestedAllowlistDecision } from "../../channel-config-C6-r_t_f.js";
import { a as resolveAllowlistMatchSimple, n as formatAllowlistMatchMeta } from "../../allowlist-match-CR4EIknA.js";
import { a as isSilentReplyText, n as SILENT_REPLY_TOKEN } from "../../tokens-Bnib3S4J.js";
import { n as extensionForMime, r as getFileExtension, t as detectMime } from "../../mime-DFfgvUW_.js";
import { u as isPrivateIpAddress } from "../../ssrf-vXCRW9rS.js";
import { n as fetchWithSsrFGuard } from "../../fetch-guard-LAmyTYUM.js";
import { S as buildMediaPayload, f as resolveOutboundMediaUrls, m as resolveSendableOutboundReplyParts } from "../../reply-payload-kJANadVo.js";
import { o as extractOriginalFilename } from "../../store-a6nK9wuy.js";
import { t as loadWebMedia } from "../../web-media-Cfnn4itl.js";
import { i as resolveToolsBySender } from "../../group-policy-D7UpbBIi.js";
import { n as writeJsonFileAtomically, t as readJsonFileWithFallback } from "../../json-store-Bv5f7usa.js";
import { n as emptyPluginConfigSchema } from "../../config-schema-2J3lBwCn.js";
import { n as resolveControlCommandGate, r as resolveDualTextControlCommandGate } from "../../command-gating-C6ON9GtF.js";
import { i as resolveMentionGatingWithBypass, n as resolveInboundMentionDecision, r as resolveMentionGating } from "../../mention-gating-CKuPxaSQ.js";
import { n as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-B6TjxQ7O.js";
import { i as mergeAllowlist, o as summarizeMapping } from "../../resolve-utils-DD3ZksVU.js";
import { n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-C6LDEhXP.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-CiUaGEwk.js";
import { a as resolveSenderScopedGroupPolicy, i as evaluateSenderGroupAccessForPolicy } from "../../group-access-CAKBAsAc.js";
import { n as readStoreAllowFromForDmPolicy, o as resolveDmGroupAccessWithLists, s as resolveEffectiveAllowFromLists } from "../../dm-policy-shared-C4gD5QZm.js";
import { a as buildPendingHistoryContextFromMap, s as clearHistoryEntriesIfEnabled, t as DEFAULT_GROUP_HISTORY_LIMIT, u as recordPendingHistoryEntryIfEnabled } from "../../history-Da8yvSVB.js";
import { n as logInboundDrop, r as logTypingFailure } from "../../logging-DmXwpYuL.js";
import { t as resolveChannelMediaMaxBytes } from "../../media-limits-Dc7-ip3g.js";
import { Q as splitSetupEntries, X as setTopLevelChannelDmPolicyWithAllowFrom, Y as setTopLevelChannelAllowFrom, Z as setTopLevelChannelGroupPolicy, t as addWildcardAllowFrom, v as mergeAllowFromEntries } from "../../setup-wizard-helpers-hupe-kT7.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-Bv-ba-Xw.js";
import { t as createChannelReplyPipeline } from "../../channel-reply-pipeline-BS4-Z0kM.js";
import { n as createChannelPairingController } from "../../channel-pairing-J21HARkM.js";
import { a as buildRuntimeAccountStatusSnapshot, d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary, n as buildBaseChannelStatusSummary } from "../../status-helpers-BJQYcoys.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-B24Yv8Dz.js";
import { n as filterSupplementalContextItems, r as shouldIncludeSupplementalContext } from "../../context-visibility-DfjuC1S9.js";
import { t as resolveChannelContextVisibilityMode } from "../../context-visibility-CckxzJ3q.js";
import { r as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-CpxBxfEs.js";
import { t as loadOutboundMediaFromUrl } from "../../outbound-media-fw18dk38.js";
import { a as isHttpsUrlAllowedByHostnameSuffixAllowlist, l as normalizeHostnameSuffixAllowlist, n as buildHostnameAllowlistPolicyFromSuffixAllowlist } from "../../ssrf-policy-CYGp1dOP.js";
import { t as chunkTextForOutbound } from "../../text-chunking-Do7UsKJv.js";
import { t as resolveInboundSessionEnvelopeContext } from "../../session-envelope-C7Z_7mWs.js";
import { n as msteamsSetupWizard, t as msteamsSetupAdapter } from "../../msteams-C-cqz4lW.js";
import { n as setMSTeamsRuntime } from "../../runtime-api-CDAvd-OB.js";
export { DEFAULT_ACCOUNT_ID, DEFAULT_GROUP_HISTORY_LIMIT, DEFAULT_WEBHOOK_MAX_BODY_BYTES, MSTeamsConfigSchema, PAIRING_APPROVED_MESSAGE, SILENT_REPLY_TOKEN, addWildcardAllowFrom, buildBaseChannelStatusSummary, buildChannelConfigSchema, buildChannelKeyCandidates, buildHostnameAllowlistPolicyFromSuffixAllowlist, buildMediaPayload, buildPendingHistoryContextFromMap, buildProbeChannelStatusSummary, buildRuntimeAccountStatusSnapshot, chunkTextForOutbound, clearHistoryEntriesIfEnabled, createChannelPairingController, createChannelReplyPipeline, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, emptyPluginConfigSchema, evaluateSenderGroupAccessForPolicy, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, filterSupplementalContextItems, formatAllowlistMatchMeta, formatDocsLink, getFileExtension, hasConfiguredSecretInput, isDangerousNameMatchingEnabled, isHttpsUrlAllowedByHostnameSuffixAllowlist, isPrivateIpAddress, isSilentReplyText, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, loadWebMedia, logInboundDrop, logTypingFailure, mergeAllowFromEntries, mergeAllowlist, msteamsSetupAdapter, msteamsSetupWizard, normalizeChannelSlug, normalizeHostnameSuffixAllowlist, normalizeResolvedSecretInputString, normalizeSecretInputString, normalizeStringEntries, readJsonFileWithFallback, readStoreAllowFromForDmPolicy, recordPendingHistoryEntryIfEnabled, resolveAllowlistMatchSimple, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelContextVisibilityMode, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveControlCommandGate, resolveDefaultGroupPolicy, resolveDmGroupAccessWithLists, resolveDualTextControlCommandGate, resolveEffectiveAllowFromLists, resolveInboundMentionDecision, resolveInboundSessionEnvelopeContext, resolveMentionGating, resolveMentionGatingWithBypass, resolveNestedAllowlistDecision, resolveOutboundMediaUrls, resolveSendableOutboundReplyParts, resolveSenderScopedGroupPolicy, resolveToolsBySender, setMSTeamsRuntime, setTopLevelChannelAllowFrom, setTopLevelChannelDmPolicyWithAllowFrom, setTopLevelChannelGroupPolicy, shouldIncludeSupplementalContext, sleep, splitSetupEntries, summarizeMapping, withFileLock, writeJsonFileAtomically };
