import { i as coerceSecretRef } from "../../types.secrets-v6szeegc.js";
import { n as ensureAuthProfileStore } from "../../store-DlTWjzi2.js";
import { n as listProfilesForProvider } from "../../profile-list-CrmV9iII.js";
import "../../provider-auth-B1YB1TFL.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-BekKSFwY.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-DC18fo2P.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-DooNMlKN.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-CBM4PyMz.js";
import "../../token-DTnYPftG.js";
import { t as fetchCopilotUsage } from "../../usage-BXTaSP9w.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
