import { a as coerceSecretRef } from "../../types.secrets-Zn5Zyn7M.js";
import { n as ensureAuthProfileStore } from "../../store-DQMFx95A.js";
import { n as listProfilesForProvider } from "../../profile-list-D_ujnDed.js";
import "../../provider-auth-D8xFOk_F.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-Dkc-_HFp.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-BChvmBon.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-C3_yRO5m.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-B9dhxeRL.js";
import "../../token-X3tG50Gp.js";
import { t as fetchCopilotUsage } from "../../usage-MCzP3zd8.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
