import { n as DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, t as DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS } from "../../timeouts-Bl23ko4G.js";
export { DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, DISCORD_DEFAULT_LISTENER_TIMEOUT_MS };
