import { t as DEFAULT_CONTEXT_TOKENS } from "../../defaults-CV5sAt-u.js";
import { i as isProxyReasoningUnsupported, n as createOpenRouterSystemCacheWrapper, r as createOpenRouterWrapper } from "../../proxy-stream-wrappers-ztu01JQX.js";
import { a as buildProviderReplayFamilyHooks } from "../../provider-model-shared-COpehvpA.js";
import { t as createProviderApiKeyAuthMethod } from "../../provider-api-key-auth-Bv_C1oBd.js";
import "../../provider-auth-api-key-DMrRWI0Y.js";
import { c as buildProviderStreamFamilyHooks, l as getOpenRouterModelCapabilities, u as loadOpenRouterModelCapabilities } from "../../provider-stream-DVrIifhg.js";
import "../../provider-stream-family-uUhuRAxC.js";
import { n as buildOpenrouterProvider } from "../../provider-catalog-DOMj6APg.js";
import { t as openrouterMediaUnderstandingProvider } from "../../media-understanding-provider-D_FjKQ62.js";
import { n as applyOpenrouterConfig, t as OPENROUTER_DEFAULT_MODEL_REF } from "../../onboard-D_JV0NKG.js";
import { t as buildOpenRouterSpeechProvider } from "../../speech-provider-CP7mtV6Y.js";
export { DEFAULT_CONTEXT_TOKENS, OPENROUTER_DEFAULT_MODEL_REF, applyOpenrouterConfig, buildOpenRouterSpeechProvider, buildOpenrouterProvider, buildProviderReplayFamilyHooks, buildProviderStreamFamilyHooks, createOpenRouterSystemCacheWrapper, createOpenRouterWrapper, createProviderApiKeyAuthMethod, getOpenRouterModelCapabilities, isProxyReasoningUnsupported, loadOpenRouterModelCapabilities, openrouterMediaUnderstandingProvider };
