import { a as coerceSecretRef } from "../../types.secrets-D9j6Z-gp.js";
import { n as ensureAuthProfileStore } from "../../store-B63eWvc7.js";
import { n as listProfilesForProvider } from "../../profile-list-CT3GwYKf.js";
import "../../provider-auth--niKqXy8.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-C0RCxGDT.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-DjZfJfmo.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-DEHpKjqH.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-Ct8isSCA.js";
import "../../token-C3Nd7qLm.js";
import { t as fetchCopilotUsage } from "../../usage-CxgZ62kd.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
