import { i as formatErrorMessage } from "../errors-Jbvi20TW.js";
import { m as resolveUserPath } from "../utils-BMRcljdi.js";
import { n as VERSION } from "../version-D108XVAk.js";
import { a as isSubagentSessionKey } from "../session-key-utils-BT0y7mVK.js";
import { m as resolveSessionAgentIds } from "../agent-scope-zHoqFGPE.js";
import { l as disposeRegisteredAgentHarnesses } from "../loader-Dbq7I8n7.js";
import { t as resolveOpenClawAgentDir } from "../agent-paths-DHYXEmd4.js";
import { n as acquireSessionWriteLock } from "../session-write-lock-DR9N7yGa.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-Dh-Zgvbs.js";
import { a as normalizeUsage } from "../usage-DyIOjex2.js";
import { r as resolveEmbeddedAgentRuntime } from "../runtime-B484LEF1.js";
import { c as resolveModelAuthMode } from "../model-auth-z9q2AAmi.js";
import { a as supportsModelTools, n as normalizeProviderToolSchemas, r as createAgentToolResultMiddlewareRunner } from "../tool-schema-runtime-Cd1hNlJv.js";
import { t as log } from "../logger-B8TPD8B9.js";
import { a as buildHarnessContextEngineRuntimeContextFromUsage, b as formatToolAggregate, c as runHarnessContextEngineMaintenance, f as extractToolResultMediaArtifact, i as buildHarnessContextEngineRuntimeContext, m as filterToolResultMediaUrls, n as assembleHarnessContextEngine, o as finalizeHarnessContextEngineTurn, r as bootstrapHarnessContextEngine, s as isActiveHarnessContextEngine, t as buildEmbeddedAttemptToolRunContext, v as isMessagingTool, y as isMessagingToolSendAction } from "../attempt.tool-run-context-BR8XSqzh.js";
import { i as emitAgentEvent } from "../agent-events-BRkCNXs1.js";
import { a as wrapToolWithBeforeToolCallHook, r as isToolWrappedWithBeforeToolCallHook } from "../pi-tools.before-tool-call-DR0s6bRU.js";
import { t as callGatewayTool } from "../gateway-DIlevtsy.js";
import { t as createOpenClawCodingTools } from "../pi-tools-BzUEo1xO.js";
import { l as setActiveEmbeddedRun, n as clearActiveEmbeddedRun, s as queueEmbeddedPiMessage, t as abortEmbeddedPiRun } from "../runs-rRV0MELk.js";
import { o as resolveSandboxContext } from "../sandbox-D2A6r4WD.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-DUOFwmAA.js";
import { n as runAgentHarnessLlmInputHook, r as runAgentHarnessLlmOutputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-BZQ5bEcQ.js";
import { a as resolveAgentHarnessBeforePromptBuildResult, i as createCodexAppServerToolResultExtensionRunner, n as formatToolProgressOutput, o as runAgentHarnessAfterCompactionHook, r as inferToolMetaFromArgs, s as runAgentHarnessBeforeCompactionHook, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS } from "../agent-harness-runtime-SHpydPw5.js";
import { a as runAgentHarnessAfterToolCallHook, o as runAgentHarnessBeforeMessageWriteHook, r as registerNativeHookRelay, t as buildNativeHookRelayCommand } from "../native-hook-relay-DGq0qKaK.js";
export { VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, clearActiveEmbeddedRun, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, inferToolMetaFromArgs, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, normalizeProviderToolSchemas, normalizeUsage, queueEmbeddedPiMessage as queueAgentHarnessMessage, registerNativeHookRelay, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveUserPath, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runHarnessContextEngineMaintenance, setActiveEmbeddedRun, supportsModelTools, wrapToolWithBeforeToolCallHook };
