import { t as DEFAULT_CONTEXT_TOKENS } from "../../defaults-CV5sAt-u.js";
import { i as isProxyReasoningUnsupported, n as createOpenRouterSystemCacheWrapper, r as createOpenRouterWrapper } from "../../proxy-stream-wrappers-fYTp5u-I.js";
import { a as buildProviderReplayFamilyHooks } from "../../provider-model-shared-Y7Lo2Cbo.js";
import { t as createProviderApiKeyAuthMethod } from "../../provider-api-key-auth-b4Vuto-0.js";
import "../../provider-auth-api-key-DRSWhA-M.js";
import { c as buildProviderStreamFamilyHooks, l as getOpenRouterModelCapabilities, u as loadOpenRouterModelCapabilities } from "../../provider-stream-ClQbXLYn.js";
import "../../provider-stream-family-BETO8tW7.js";
import { n as buildOpenrouterProvider } from "../../provider-catalog-ebTk0qVf.js";
import { t as openrouterMediaUnderstandingProvider } from "../../media-understanding-provider-Dl49Uae7.js";
import { n as applyOpenrouterConfig, t as OPENROUTER_DEFAULT_MODEL_REF } from "../../onboard-80lQWomF.js";
import { t as buildOpenRouterSpeechProvider } from "../../speech-provider-DR3LoAcx.js";
export { DEFAULT_CONTEXT_TOKENS, OPENROUTER_DEFAULT_MODEL_REF, applyOpenrouterConfig, buildOpenRouterSpeechProvider, buildOpenrouterProvider, buildProviderReplayFamilyHooks, buildProviderStreamFamilyHooks, createOpenRouterSystemCacheWrapper, createOpenRouterWrapper, createProviderApiKeyAuthMethod, getOpenRouterModelCapabilities, isProxyReasoningUnsupported, loadOpenRouterModelCapabilities, openrouterMediaUnderstandingProvider };
