import { a as coerceSecretRef } from "../../types.secrets-Zn5Zyn7M.js";
import { n as ensureAuthProfileStore } from "../../store-DQMFx95A.js";
import { n as listProfilesForProvider } from "../../profile-list-D_ujnDed.js";
import "../../provider-auth-DtsxgrdK.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-gVWDI1LW.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-CNxKrmqC.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-BLljQTnk.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-CiLmQwZY.js";
import "../../token-PjPLvGKb.js";
import { t as fetchCopilotUsage } from "../../usage-BqXYdwk8.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
