import { t as DEFAULT_CONTEXT_TOKENS } from "../../defaults-DM8yIn8C.js";
import { i as isProxyReasoningUnsupported, n as createOpenRouterSystemCacheWrapper, r as createOpenRouterWrapper } from "../../proxy-stream-wrappers-7FHiy56D.js";
import { a as buildProviderReplayFamilyHooks } from "../../provider-model-shared-CIbJhChi.js";
import { t as createProviderApiKeyAuthMethod } from "../../provider-api-key-auth-BxCydrTQ.js";
import "../../provider-auth-api-key-D2Wfwx18.js";
import { c as buildProviderStreamFamilyHooks, l as getOpenRouterModelCapabilities, u as loadOpenRouterModelCapabilities } from "../../provider-stream-C4dC_jZ6.js";
import "../../provider-stream-family-CzJPBIQh.js";
import { n as buildOpenrouterProvider } from "../../provider-catalog-tf6O4LlM.js";
import { t as openrouterMediaUnderstandingProvider } from "../../media-understanding-provider-CnLz5MaR.js";
import { n as applyOpenrouterConfig, t as OPENROUTER_DEFAULT_MODEL_REF } from "../../onboard-BW_jhO1m.js";
import { t as buildOpenRouterSpeechProvider } from "../../speech-provider-CPd_WOCC.js";
export { DEFAULT_CONTEXT_TOKENS, OPENROUTER_DEFAULT_MODEL_REF, applyOpenrouterConfig, buildOpenRouterSpeechProvider, buildOpenrouterProvider, buildProviderReplayFamilyHooks, buildProviderStreamFamilyHooks, createOpenRouterSystemCacheWrapper, createOpenRouterWrapper, createProviderApiKeyAuthMethod, getOpenRouterModelCapabilities, isProxyReasoningUnsupported, loadOpenRouterModelCapabilities, openrouterMediaUnderstandingProvider };
