import { t as DEFAULT_CONTEXT_TOKENS } from "../../defaults-Db0k6oKb.js";
import { i as isProxyReasoningUnsupported, n as createOpenRouterSystemCacheWrapper, r as createOpenRouterWrapper } from "../../proxy-stream-wrappers-Bnn8iaYe.js";
import { a as buildProviderReplayFamilyHooks } from "../../provider-model-shared-BupW1wb7.js";
import { t as createProviderApiKeyAuthMethod } from "../../provider-api-key-auth-Bbu5LfOo.js";
import "../../provider-auth-api-key-DQU3NqC7.js";
import { c as buildProviderStreamFamilyHooks, l as getOpenRouterModelCapabilities, u as loadOpenRouterModelCapabilities } from "../../provider-stream-7r7lsYUh.js";
import "../../provider-stream-family-QY18RRj8.js";
import { n as buildOpenrouterProvider } from "../../provider-catalog-BR5GF68P.js";
import { t as openrouterMediaUnderstandingProvider } from "../../media-understanding-provider-DSr5hUwR.js";
import { n as applyOpenrouterConfig, t as OPENROUTER_DEFAULT_MODEL_REF } from "../../onboard-BMZama_-.js";
export { DEFAULT_CONTEXT_TOKENS, OPENROUTER_DEFAULT_MODEL_REF, applyOpenrouterConfig, buildOpenrouterProvider, buildProviderReplayFamilyHooks, buildProviderStreamFamilyHooks, createOpenRouterSystemCacheWrapper, createOpenRouterWrapper, createProviderApiKeyAuthMethod, getOpenRouterModelCapabilities, isProxyReasoningUnsupported, loadOpenRouterModelCapabilities, openrouterMediaUnderstandingProvider };
