import { o as resolveRequiredHomeDir } from "../home-dir-CfZ08GnU.js";
import { a as hasConfiguredSecretInput, i as coerceSecretRef } from "../types.secrets-v6szeegc.js";
import { l as resolveDefaultSecretProviderAlias } from "../ref-contract-cHj1Typp.js";
import { i as omitEnvKeysCaseInsensitive, n as listKnownProviderAuthEnvVarNames } from "../provider-env-vars-b8Gq5FEE.js";
import { A as CLAUDE_CLI_PROFILE_ID, C as DEFAULT_OAUTH_REFRESH_MARGIN_MS, D as readClaudeCliCredentialsCached, T as hasUsableOAuthCredential, j as CODEX_CLI_PROFILE_ID, n as ensureAuthProfileStore, r as ensureAuthProfileStoreForLocalUpdate } from "../store-DlTWjzi2.js";
import { t as resolveOpenClawAgentDir } from "../agent-paths-DGDPUqkd.js";
import { _ as resolveOAuthApiKeyMarker, h as resolveNonEnvSecretRefApiKeyMarker, l as isKnownEnvApiKeyMarker, r as MINIMAX_OAUTH_MARKER, t as CUSTOM_LOCAL_AUTH_MARKER, u as isNonSecretApiKeyMarker } from "../model-auth-markers-OFrmb6OJ.js";
import { n as normalizeSecretInput, t as normalizeOptionalSecretInput } from "../normalize-secret-input-D5XzKQ7M.js";
import { t as resolveEnvApiKey } from "../model-auth-env-M4IsLhMq.js";
import { r as normalizeApiKeyConfig } from "../models-config.providers.secrets-ehy8roEZ.js";
import { n as listProfilesForProvider } from "../profile-list-CrmV9iII.js";
import { n as suggestOAuthProfileIdForLegacyDefault } from "../repair-D2iCJ4o9.js";
import { a as upsertAuthProfileWithLock, i as upsertAuthProfile, n as removeProviderAuthProfilesWithLock } from "../profiles-ByOh6QBz.js";
import { t as resolveSecretInputModeForEnvSelection } from "../provider-auth-mode-BlKrwUBq.js";
import { n as promptSecretRefForSetup } from "../provider-auth-ref-DdxVesl_.js";
import { a as normalizeSecretInputModeInput, i as normalizeApiKeyInput, n as ensureApiKeyFromOptionEnvOrPrompt, r as formatApiKeyPreview, s as validateApiKeyInput, t as ensureApiKeyFromEnvOrPrompt } from "../provider-auth-input-_FirplOd.js";
import { n as validateAnthropicSetupToken, t as buildTokenProfileId } from "../provider-auth-token-BdODftGa.js";
import { i as writeOAuthCredentials, n as buildApiKeyCredential, r as upsertApiKeyProfile, t as applyAuthProfileConfig } from "../provider-auth-helpers-EeCBEk18.js";
import { t as createProviderApiKeyAuthMethod } from "../provider-api-key-auth-Bbu5LfOo.js";
import { t as buildOauthProviderAuthResult } from "../provider-auth-result-DnK4YBYd.js";
import { i as toFormUrlEncoded, n as generateHexPkceVerifierChallenge, r as generatePkceVerifierChallenge, t as isProviderApiKeyConfigured } from "../provider-auth-B1YB1TFL.js";
export { CLAUDE_CLI_PROFILE_ID, CODEX_CLI_PROFILE_ID, CUSTOM_LOCAL_AUTH_MARKER, DEFAULT_OAUTH_REFRESH_MARGIN_MS, MINIMAX_OAUTH_MARKER, applyAuthProfileConfig, buildApiKeyCredential, buildOauthProviderAuthResult, buildTokenProfileId, coerceSecretRef, createProviderApiKeyAuthMethod, ensureApiKeyFromEnvOrPrompt, ensureApiKeyFromOptionEnvOrPrompt, ensureAuthProfileStore, ensureAuthProfileStoreForLocalUpdate, formatApiKeyPreview, generateHexPkceVerifierChallenge, generatePkceVerifierChallenge, hasConfiguredSecretInput, hasUsableOAuthCredential, isKnownEnvApiKeyMarker, isNonSecretApiKeyMarker, isProviderApiKeyConfigured, listKnownProviderAuthEnvVarNames, listProfilesForProvider, normalizeApiKeyConfig, normalizeApiKeyInput, normalizeOptionalSecretInput, normalizeSecretInput, normalizeSecretInputModeInput, omitEnvKeysCaseInsensitive, promptSecretRefForSetup, readClaudeCliCredentialsCached, removeProviderAuthProfilesWithLock, resolveDefaultSecretProviderAlias, resolveEnvApiKey, resolveNonEnvSecretRefApiKeyMarker, resolveOAuthApiKeyMarker, resolveOpenClawAgentDir, resolveRequiredHomeDir, resolveSecretInputModeForEnvSelection, suggestOAuthProfileIdForLegacyDefault, toFormUrlEncoded, upsertApiKeyProfile, upsertAuthProfile, upsertAuthProfileWithLock, validateAnthropicSetupToken, validateApiKeyInput, writeOAuthCredentials };
