import { a as coerceSecretRef } from "../../types.secrets-D9j6Z-gp.js";
import { n as ensureAuthProfileStore } from "../../store-DWcsUxbV.js";
import { n as listProfilesForProvider } from "../../profile-list-Bg_34ywG.js";
import "../../provider-auth--wHTFrUi.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-CNi3rbIy.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-BYHuJxEE.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-HT8XZSkR.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-DW5TfMwd.js";
import "../../token-C0V3XPZF.js";
import { t as fetchCopilotUsage } from "../../usage-BAK0xfbS.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
