import { t as createSubsystemLogger } from "../subsystem-CJBoMDt5.js";
import { u as resolveGatewayPort } from "../paths-D92DjaZ-.js";
import { o as isSecretRef } from "../types.secrets-BZ6RGKR0.js";
import { l as isTrustedProxyAddress, p as resolveClientIp } from "../net-B-vYkUV_.js";
import { i as normalizeHyphenSlug, n as normalizeAtHashSlug } from "../string-normalization-5F-0OqbT.js";
import { a as emptyChannelConfigSchema, r as buildChannelConfigSchema } from "../config-schema-Bx16NlRy.js";
import { d as resolveThreadSessionKeys } from "../session-key-Cn2QoOyX.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-BM1T6029.js";
import { i as parseStrictPositiveInteger } from "../parse-finite-number-DdG2XOLD.js";
import { n as resolveGlobalDedupeCache, t as createDedupeCache } from "../dedupe-JnXqffpw.js";
import { n as delegateCompactionToRuntime, t as buildMemorySystemPromptAddition } from "../delegate-CmA92lyo.js";
import { a as createActionGate, f as readNumberParam, g as readStringParam, l as jsonResult, m as readStringArrayParam, p as readReactionParams } from "../common-BGcbYPyw.js";
import { i as stringEnum, n as channelTargetsSchema, r as optionalStringEnum, t as channelTargetSchema } from "../typebox-CXPMnHfa.js";
import { a as generateSecureUuid, i as generateSecureToken } from "../secure-random-bHiMyod8.js";
import { n as deleteAccountFromConfigSection, r as setAccountEnabledInConfigSection, t as clearAccountEntryFields } from "../config-helpers-BzagItDT.js";
import { n as formatPairingApproveHint, r as parseOptionalDelimitedEntries } from "../helpers-DIuSKnxZ.js";
import { t as buildAgentSessionKey } from "../resolve-route-DNbrhMiq.js";
import { n as emptyPluginConfigSchema, t as buildPluginConfigSchema } from "../config-schema-TbKbeW26.js";
import { t as definePluginEntry } from "../plugin-entry-C5CNAgRN.js";
import { n as enqueueKeyedTask, t as KeyedAsyncQueue } from "../keyed-async-queue-5zUy79xp.js";
import { s as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-Ch6SdLT5.js";
import { a as readSecretFileSync, i as loadSecretFileSync, o as tryReadSecretFileSync, t as DEFAULT_SECRET_FILE_MAX_BYTES } from "../secret-file-Ceekl8PS.js";
import { n as resolveGatewayBindUrl, t as resolveTailnetHostWithRunner } from "../tailscale-status-BwAYvVL1.js";
import { n as formatZonedTimestamp } from "../format-datetime-CUTHGQIl.js";
import { t as resolveConfiguredAcpBindingRecord } from "../persistent-bindings.resolve-CXsYQAYg.js";
import { a as defineChannelPluginEntry, c as getChatChannelMeta, d as stripTargetKindPrefix, i as createChatChannelPlugin, l as recoverCurrentThreadSessionId, n as buildThreadAwareOutboundSessionRoute, o as defineSetupPluginEntry, r as createChannelPluginBase, s as ensureConfiguredAcpBindingReady, t as buildChannelOutboundSessionRoute, u as stripChannelTargetPrefix } from "../core-DDydeSSz.js";
export { DEFAULT_ACCOUNT_ID, DEFAULT_SECRET_FILE_MAX_BYTES, KeyedAsyncQueue, applyAccountNameToChannelSection, buildAgentSessionKey, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildMemorySystemPromptAddition, buildPluginConfigSchema, buildThreadAwareOutboundSessionRoute, channelTargetSchema, channelTargetsSchema, clearAccountEntryFields, createActionGate, createChannelPluginBase, createChatChannelPlugin, createDedupeCache, createSubsystemLogger, defineChannelPluginEntry, definePluginEntry, defineSetupPluginEntry, delegateCompactionToRuntime, deleteAccountFromConfigSection, emptyChannelConfigSchema, emptyPluginConfigSchema, enqueueKeyedTask, ensureConfiguredAcpBindingReady, formatPairingApproveHint, formatZonedTimestamp, generateSecureToken, generateSecureUuid, getChatChannelMeta, isSecretRef, isTrustedProxyAddress, jsonResult, loadSecretFileSync, migrateBaseNameToDefaultAccount, normalizeAccountId, normalizeAtHashSlug, normalizeHyphenSlug, optionalStringEnum, parseOptionalDelimitedEntries, parseStrictPositiveInteger, readNumberParam, readReactionParams, readSecretFileSync, readStringArrayParam, readStringParam, recoverCurrentThreadSessionId, resolveClientIp, resolveConfiguredAcpBindingRecord, resolveGatewayBindUrl, resolveGatewayPort, resolveGlobalDedupeCache, resolveTailnetHostWithRunner, resolveThreadSessionKeys, setAccountEnabledInConfigSection, stringEnum, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };
