import { o as resolveRequiredHomeDir } from "../home-dir-C44RaPME.js";
import { a as hasConfiguredSecretInput, i as coerceSecretRef } from "../types.secrets-BZ6RGKR0.js";
import { l as resolveDefaultSecretProviderAlias } from "../ref-contract-CsOjNPCR.js";
import { i as omitEnvKeysCaseInsensitive, n as listKnownProviderAuthEnvVarNames } from "../provider-env-vars-D-KHlttz.js";
import { A as CLAUDE_CLI_PROFILE_ID, C as DEFAULT_OAUTH_REFRESH_MARGIN_MS, D as readClaudeCliCredentialsCached, T as hasUsableOAuthCredential, j as CODEX_CLI_PROFILE_ID, n as ensureAuthProfileStore, r as ensureAuthProfileStoreForLocalUpdate } from "../store-De_brRTx.js";
import { t as resolveOpenClawAgentDir } from "../agent-paths-yYk0N-bh.js";
import { _ as resolveOAuthApiKeyMarker, h as resolveNonEnvSecretRefApiKeyMarker, l as isKnownEnvApiKeyMarker, r as MINIMAX_OAUTH_MARKER, t as CUSTOM_LOCAL_AUTH_MARKER, u as isNonSecretApiKeyMarker } from "../model-auth-markers-U2294Wcj.js";
import { n as normalizeSecretInput, t as normalizeOptionalSecretInput } from "../normalize-secret-input-k9H_9vvf.js";
import { t as resolveEnvApiKey } from "../model-auth-env-BPk5alE5.js";
import { r as normalizeApiKeyConfig } from "../models-config.providers.secrets-Ct7ZKt47.js";
import { i as removeProviderAuthProfilesWithLock, n as listProfilesForProvider, o as upsertAuthProfile, s as upsertAuthProfileWithLock } from "../profiles-DQiFenPb.js";
import { n as suggestOAuthProfileIdForLegacyDefault } from "../repair-DTHk4iey.js";
import { t as resolveSecretInputModeForEnvSelection } from "../provider-auth-mode-CXaNg9I8.js";
import { n as promptSecretRefForSetup } from "../provider-auth-ref-CwZkI6xM.js";
import { a as normalizeSecretInputModeInput, i as normalizeApiKeyInput, n as ensureApiKeyFromOptionEnvOrPrompt, r as formatApiKeyPreview, s as validateApiKeyInput, t as ensureApiKeyFromEnvOrPrompt } from "../provider-auth-input-HohW9v1U.js";
import { n as validateAnthropicSetupToken, t as buildTokenProfileId } from "../provider-auth-token-CPtxkRrr.js";
import { i as writeOAuthCredentials, n as buildApiKeyCredential, r as upsertApiKeyProfile, t as applyAuthProfileConfig } from "../provider-auth-helpers-DDc3aiuG.js";
import { t as createProviderApiKeyAuthMethod } from "../provider-api-key-auth-D7SXhgzu.js";
import { t as buildOauthProviderAuthResult } from "../provider-auth-result-vlHGkP0M.js";
import { i as toFormUrlEncoded, n as generateHexPkceVerifierChallenge, r as generatePkceVerifierChallenge, t as isProviderApiKeyConfigured } from "../provider-auth-Co_LMlTd.js";
export { CLAUDE_CLI_PROFILE_ID, CODEX_CLI_PROFILE_ID, CUSTOM_LOCAL_AUTH_MARKER, DEFAULT_OAUTH_REFRESH_MARGIN_MS, MINIMAX_OAUTH_MARKER, applyAuthProfileConfig, buildApiKeyCredential, buildOauthProviderAuthResult, buildTokenProfileId, coerceSecretRef, createProviderApiKeyAuthMethod, ensureApiKeyFromEnvOrPrompt, ensureApiKeyFromOptionEnvOrPrompt, ensureAuthProfileStore, ensureAuthProfileStoreForLocalUpdate, formatApiKeyPreview, generateHexPkceVerifierChallenge, generatePkceVerifierChallenge, hasConfiguredSecretInput, hasUsableOAuthCredential, isKnownEnvApiKeyMarker, isNonSecretApiKeyMarker, isProviderApiKeyConfigured, listKnownProviderAuthEnvVarNames, listProfilesForProvider, normalizeApiKeyConfig, normalizeApiKeyInput, normalizeOptionalSecretInput, normalizeSecretInput, normalizeSecretInputModeInput, omitEnvKeysCaseInsensitive, promptSecretRefForSetup, readClaudeCliCredentialsCached, removeProviderAuthProfilesWithLock, resolveDefaultSecretProviderAlias, resolveEnvApiKey, resolveNonEnvSecretRefApiKeyMarker, resolveOAuthApiKeyMarker, resolveOpenClawAgentDir, resolveRequiredHomeDir, resolveSecretInputModeForEnvSelection, suggestOAuthProfileIdForLegacyDefault, toFormUrlEncoded, upsertApiKeyProfile, upsertAuthProfile, upsertAuthProfileWithLock, validateAnthropicSetupToken, validateApiKeyInput, writeOAuthCredentials };
