import { t as createSubsystemLogger } from "../subsystem-DRUx3zf3.js";
import { u as resolveGatewayPort } from "../paths-CrDgDBYA.js";
import { s as isSecretRef } from "../types.secrets-D9j6Z-gp.js";
import { l as isTrustedProxyAddress, p as resolveClientIp } from "../net-lcLTXl0l.js";
import { i as normalizeHyphenSlug, n as normalizeAtHashSlug } from "../string-normalization-CEOVTwLJ.js";
import { a as emptyChannelConfigSchema, r as buildChannelConfigSchema } from "../config-schema-OPypi1r3.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-C3j_3_su.js";
import { d as resolveThreadSessionKeys } from "../session-key-EpIbK3Oz.js";
import { i as parseStrictPositiveInteger } from "../parse-finite-number-BbGMkOzg.js";
import { n as resolveGlobalDedupeCache, t as createDedupeCache } from "../dedupe-C8W1hL3A.js";
import { n as delegateCompactionToRuntime, t as buildMemorySystemPromptAddition } from "../delegate-C2Cl6kCB.js";
import { a as createActionGate, f as readNumberParam, g as readStringParam, l as jsonResult, m as readStringArrayParam, p as readReactionParams } from "../common-B-ADznUd.js";
import { i as stringEnum, n as channelTargetsSchema, r as optionalStringEnum, t as channelTargetSchema } from "../typebox-CjOhKOr9.js";
import { a as generateSecureToken, o as generateSecureUuid } from "../secure-random-aGuoGZ0m.js";
import { n as deleteAccountFromConfigSection, r as setAccountEnabledInConfigSection, t as clearAccountEntryFields } from "../config-helpers-xGgW25ph.js";
import { n as formatPairingApproveHint, r as parseOptionalDelimitedEntries } from "../helpers-B7mjmIZr.js";
import { t as buildAgentSessionKey } from "../resolve-route-BQHyc8Rb.js";
import { n as emptyPluginConfigSchema, t as buildPluginConfigSchema } from "../config-schema-Db8uIJi-.js";
import { t as definePluginEntry } from "../plugin-entry-BMrQ8lmP.js";
import { n as enqueueKeyedTask, t as KeyedAsyncQueue } from "../keyed-async-queue-dmPG7e-O.js";
import { s as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-P3bVHWjM.js";
import { a as readSecretFileSync, i as loadSecretFileSync, o as tryReadSecretFileSync, t as DEFAULT_SECRET_FILE_MAX_BYTES } from "../secret-file-CHYb9iSl.js";
import { n as resolveGatewayBindUrl, t as resolveTailnetHostWithRunner } from "../tailscale-status-BATwXqC1.js";
import { n as formatZonedTimestamp } from "../format-datetime-BvThnfBM.js";
import { t as resolveConfiguredAcpBindingRecord } from "../persistent-bindings.resolve-Bm3OUF3O.js";
import { a as defineChannelPluginEntry, c as getChatChannelMeta, d as stripTargetKindPrefix, i as createChatChannelPlugin, l as recoverCurrentThreadSessionId, n as buildThreadAwareOutboundSessionRoute, o as defineSetupPluginEntry, r as createChannelPluginBase, s as ensureConfiguredAcpBindingReady, t as buildChannelOutboundSessionRoute, u as stripChannelTargetPrefix } from "../core-C1EU-l7z.js";
export { DEFAULT_ACCOUNT_ID, DEFAULT_SECRET_FILE_MAX_BYTES, KeyedAsyncQueue, applyAccountNameToChannelSection, buildAgentSessionKey, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildMemorySystemPromptAddition, buildPluginConfigSchema, buildThreadAwareOutboundSessionRoute, channelTargetSchema, channelTargetsSchema, clearAccountEntryFields, createActionGate, createChannelPluginBase, createChatChannelPlugin, createDedupeCache, createSubsystemLogger, defineChannelPluginEntry, definePluginEntry, defineSetupPluginEntry, delegateCompactionToRuntime, deleteAccountFromConfigSection, emptyChannelConfigSchema, emptyPluginConfigSchema, enqueueKeyedTask, ensureConfiguredAcpBindingReady, formatPairingApproveHint, formatZonedTimestamp, generateSecureToken, generateSecureUuid, getChatChannelMeta, isSecretRef, isTrustedProxyAddress, jsonResult, loadSecretFileSync, migrateBaseNameToDefaultAccount, normalizeAccountId, normalizeAtHashSlug, normalizeHyphenSlug, optionalStringEnum, parseOptionalDelimitedEntries, parseStrictPositiveInteger, readNumberParam, readReactionParams, readSecretFileSync, readStringArrayParam, readStringParam, recoverCurrentThreadSessionId, resolveClientIp, resolveConfiguredAcpBindingRecord, resolveGatewayBindUrl, resolveGatewayPort, resolveGlobalDedupeCache, resolveTailnetHostWithRunner, resolveThreadSessionKeys, setAccountEnabledInConfigSection, stringEnum, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };
