import { o as resolveRequiredHomeDir } from "../home-dir-CfZ08GnU.js";
import { a as coerceSecretRef, o as hasConfiguredSecretInput } from "../types.secrets-D9j6Z-gp.js";
import { l as resolveDefaultSecretProviderAlias } from "../ref-contract-CmDf3_tu.js";
import { i as omitEnvKeysCaseInsensitive, n as listKnownProviderAuthEnvVarNames } from "../provider-env-vars-Cva53EUa.js";
import { A as CLAUDE_CLI_PROFILE_ID, C as DEFAULT_OAUTH_REFRESH_MARGIN_MS, D as readClaudeCliCredentialsCached, T as hasUsableOAuthCredential, j as CODEX_CLI_PROFILE_ID, n as ensureAuthProfileStore, r as ensureAuthProfileStoreForLocalUpdate } from "../store-B63eWvc7.js";
import { t as resolveOpenClawAgentDir } from "../agent-paths-DHYXEmd4.js";
import { _ as resolveOAuthApiKeyMarker, h as resolveNonEnvSecretRefApiKeyMarker, l as isKnownEnvApiKeyMarker, r as MINIMAX_OAUTH_MARKER, t as CUSTOM_LOCAL_AUTH_MARKER, u as isNonSecretApiKeyMarker } from "../model-auth-markers-9f2IFvuI.js";
import { n as normalizeSecretInput, t as normalizeOptionalSecretInput } from "../normalize-secret-input-CkOd5v2f.js";
import { t as resolveEnvApiKey } from "../model-auth-env-BsMQtO3H.js";
import { r as normalizeApiKeyConfig } from "../models-config.providers.secrets-Ca6Fs1Et.js";
import { n as listProfilesForProvider } from "../profile-list-CT3GwYKf.js";
import { n as suggestOAuthProfileIdForLegacyDefault } from "../repair-Dz-bQ24r.js";
import { a as upsertAuthProfileWithLock, i as upsertAuthProfile, n as removeProviderAuthProfilesWithLock } from "../profiles-DjXPV26S.js";
import { t as resolveSecretInputModeForEnvSelection } from "../provider-auth-mode-B44uLvaO.js";
import { n as promptSecretRefForSetup } from "../provider-auth-ref-BQ3DoMen.js";
import { a as normalizeSecretInputModeInput, i as normalizeApiKeyInput, n as ensureApiKeyFromOptionEnvOrPrompt, r as formatApiKeyPreview, s as validateApiKeyInput, t as ensureApiKeyFromEnvOrPrompt } from "../provider-auth-input-Le2omKFf.js";
import { n as validateAnthropicSetupToken, t as buildTokenProfileId } from "../provider-auth-token-Boa07xSj.js";
import { i as writeOAuthCredentials, n as buildApiKeyCredential, r as upsertApiKeyProfile, t as applyAuthProfileConfig } from "../provider-auth-helpers-D4xTC7qE.js";
import { t as createProviderApiKeyAuthMethod } from "../provider-api-key-auth-CCxyCMer.js";
import { t as buildOauthProviderAuthResult } from "../provider-auth-result-BSeCrdal.js";
import { i as toFormUrlEncoded, n as generateHexPkceVerifierChallenge, r as generatePkceVerifierChallenge, t as isProviderApiKeyConfigured } from "../provider-auth--niKqXy8.js";
export { CLAUDE_CLI_PROFILE_ID, CODEX_CLI_PROFILE_ID, CUSTOM_LOCAL_AUTH_MARKER, DEFAULT_OAUTH_REFRESH_MARGIN_MS, MINIMAX_OAUTH_MARKER, applyAuthProfileConfig, buildApiKeyCredential, buildOauthProviderAuthResult, buildTokenProfileId, coerceSecretRef, createProviderApiKeyAuthMethod, ensureApiKeyFromEnvOrPrompt, ensureApiKeyFromOptionEnvOrPrompt, ensureAuthProfileStore, ensureAuthProfileStoreForLocalUpdate, formatApiKeyPreview, generateHexPkceVerifierChallenge, generatePkceVerifierChallenge, hasConfiguredSecretInput, hasUsableOAuthCredential, isKnownEnvApiKeyMarker, isNonSecretApiKeyMarker, isProviderApiKeyConfigured, listKnownProviderAuthEnvVarNames, listProfilesForProvider, normalizeApiKeyConfig, normalizeApiKeyInput, normalizeOptionalSecretInput, normalizeSecretInput, normalizeSecretInputModeInput, omitEnvKeysCaseInsensitive, promptSecretRefForSetup, readClaudeCliCredentialsCached, removeProviderAuthProfilesWithLock, resolveDefaultSecretProviderAlias, resolveEnvApiKey, resolveNonEnvSecretRefApiKeyMarker, resolveOAuthApiKeyMarker, resolveOpenClawAgentDir, resolveRequiredHomeDir, resolveSecretInputModeForEnvSelection, suggestOAuthProfileIdForLegacyDefault, toFormUrlEncoded, upsertApiKeyProfile, upsertAuthProfile, upsertAuthProfileWithLock, validateAnthropicSetupToken, validateApiKeyInput, writeOAuthCredentials };
