import { i as formatErrorMessage } from "../errors-Jbvi20TW.js";
import { m as resolveUserPath } from "../utils-BMRcljdi.js";
import { n as VERSION } from "../version-DZq9J0ei.js";
import { a as isSubagentSessionKey } from "../session-key-utils-BT0y7mVK.js";
import { m as resolveSessionAgentIds } from "../agent-scope-_6dFncNS.js";
import { l as disposeRegisteredAgentHarnesses } from "../loader-NucjcOgv.js";
import { t as resolveOpenClawAgentDir } from "../agent-paths-Df60yWjf.js";
import { n as acquireSessionWriteLock } from "../session-write-lock-CAy2l2rJ.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-ofiGBxi_.js";
import { i as emitAgentEvent } from "../agent-events-DMk-SEBA.js";
import { a as normalizeUsage } from "../usage-xVEV8sHL.js";
import { r as resolveEmbeddedAgentRuntime } from "../runtime-mIW-LQTp.js";
import { c as resolveModelAuthMode } from "../model-auth-CMq_TSIy.js";
import { a as supportsModelTools, n as normalizeProviderToolSchemas, r as createAgentToolResultMiddlewareRunner } from "../tool-schema-runtime-DOOb8IQw.js";
import { t as log } from "../logger-BGiI50uA.js";
import { a as buildHarnessContextEngineRuntimeContextFromUsage, b as formatToolAggregate, c as runHarnessContextEngineMaintenance, f as extractToolResultMediaArtifact, i as buildHarnessContextEngineRuntimeContext, m as filterToolResultMediaUrls, n as assembleHarnessContextEngine, o as finalizeHarnessContextEngineTurn, r as bootstrapHarnessContextEngine, s as isActiveHarnessContextEngine, t as buildEmbeddedAttemptToolRunContext, v as isMessagingTool, y as isMessagingToolSendAction } from "../attempt.tool-run-context-u4DLZCLf.js";
import { a as wrapToolWithBeforeToolCallHook, r as isToolWrappedWithBeforeToolCallHook } from "../pi-tools.before-tool-call-BlTW1O8w.js";
import { t as callGatewayTool } from "../gateway-Be16iQej.js";
import { t as createOpenClawCodingTools } from "../pi-tools-fJ-5XJbT.js";
import { l as setActiveEmbeddedRun, n as clearActiveEmbeddedRun, s as queueEmbeddedPiMessage, t as abortEmbeddedPiRun } from "../runs-D5h4YOhz.js";
import { o as resolveSandboxContext } from "../sandbox-mpsArbFr.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-BUzOohOk.js";
import { t as formatApprovalDisplayPath } from "../approval-display-paths-8kMELGsg.js";
import { n as runAgentHarnessLlmInputHook, r as runAgentHarnessLlmOutputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-DlOJDyTb.js";
import { a as resolveAgentHarnessBeforePromptBuildResult, i as createCodexAppServerToolResultExtensionRunner, n as formatToolProgressOutput, o as runAgentHarnessAfterCompactionHook, r as inferToolMetaFromArgs, s as runAgentHarnessBeforeCompactionHook, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS } from "../agent-harness-runtime-CS3ryKXr.js";
import { a as runAgentHarnessAfterToolCallHook, o as runAgentHarnessBeforeMessageWriteHook, r as registerNativeHookRelay, t as buildNativeHookRelayCommand } from "../native-hook-relay-zB9Yio9X.js";
export { VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, clearActiveEmbeddedRun, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatApprovalDisplayPath, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, inferToolMetaFromArgs, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, normalizeProviderToolSchemas, normalizeUsage, queueEmbeddedPiMessage as queueAgentHarnessMessage, registerNativeHookRelay, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveUserPath, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runHarnessContextEngineMaintenance, setActiveEmbeddedRun, supportsModelTools, wrapToolWithBeforeToolCallHook };
