import { i as coerceSecretRef } from "../../types.secrets-BZ6RGKR0.js";
import { n as ensureAuthProfileStore } from "../../store-De_brRTx.js";
import { n as listProfilesForProvider } from "../../profiles-DQiFenPb.js";
import "../../provider-auth-Co_LMlTd.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-BuTjCO5R.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-CY_6sFno.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-ClffXTnz.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-DlRFq27f.js";
import "../../token-ChJ2qhzx.js";
import { t as fetchCopilotUsage } from "../../usage-DdZ0jNh8.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
